DECLARE @user_guid UNIQUEIDENTIFIER;
DECLARE @user_id VARCHAR(30);
DECLARE @email VARCHAR(30);
DECLARE @datetime DATETIME;

SET @user_guid = '<USER GUID>';
SET @user_id = '<IDIR USER ID>';
SET @email = '<IDIR EMAIL ADDRESS>';
SET @datetime = GETDATE();

INSERT INTO [HMR_DEV].[dbo].[HMR_SYSTEM_USER] 
	([SYSTEM_USER_ID]
	,[USER_GUID]
	,[USERNAME]
	,[USER_DIRECTORY]
	,[USER_TYPE]
	,[EMAIL]
	,[CONCURRENCY_CONTROL_NUMBER]
	,[APP_CREATE_USERID]
	,[APP_CREATE_TIMESTAMP]
	,[APP_CREATE_USER_GUID]
	,[APP_CREATE_USER_DIRECTORY]
	,[APP_LAST_UPDATE_USERID]
	,[APP_LAST_UPDATE_TIMESTAMP]
	,[APP_LAST_UPDATE_USER_GUID]
	,[APP_LAST_UPDATE_USER_DIRECTORY]) 
VALUES
	(1
	,@user_guid
	,@user_id
	,'IDIR'
	,'INTERNAL'
	,@email
	,1
	,@user_id
	,@datetime
	,@user_guid
	,'IDIR'
	,@user_id
	,@datetime
	,@user_guid
	,'IDIR')

INSERT INTO [HMR_DEV].[dbo].[HMR_USER_ROLE]
	([USER_ROLE_ID]
	,[ROLE_ID]
	,[SYSTEM_USER_ID]
	,[CONCURRENCY_CONTROL_NUMBER]
	,[APP_CREATE_USERID]
	,[APP_CREATE_TIMESTAMP]
	,[APP_CREATE_USER_GUID]
	,[APP_CREATE_USER_DIRECTORY]
	,[APP_LAST_UPDATE_USERID]
	,[APP_LAST_UPDATE_TIMESTAMP]
	,[APP_LAST_UPDATE_USER_GUID]
	,[APP_LAST_UPDATE_USER_DIRECTORY])
VALUES
	(1
	,1
	,1
	,1
	,@user_id
	,@datetime
	,@user_guid
	,'IDIR'
	,@user_id
	,@datetime
	,@user_guid
	,'IDIR')
